version: '3'

services:
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    hostname: influxdb
    volumes:
      - ./_influx.db:/var/lib
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=influxdb
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=influxdb
